Pa 09 add get user endpoint
TastyKawusia/PartyApp pull request #10
Opened 2023-04-12 12:28 UTC by des1ro

Need to preview

2023-04-16 00:08 UTC, adamsmichal requested changes

2023-04-16 00:08 UTC, adamsmichal commented on src/user/user.routing.ts
> +  const idd: number = parseInt(id);
Lepszą praktyką będzie jeśli zrobimy jedną zmienną zamiast dwóch. `const id = parseInt(req.params.id);`. Dodatkowo zwróć uwagę że nie musisz typować zmiennej jawnie (const id: number <-- w ten sposób nie musisz). Zobacz sobie że jak najedziesz kursorem na id to wyświetli się że jest typu number a jak usuniesz adnotację typu czyli zostanie `const id` samo to też jak najedziesz to będziesz miał że to jest number. Typescript sam się domyśli jakiego typu jest zmienna. Jeśli po najechaniu na zmienną nie pokazuje Ci się jej typ to musisz zainstalować wtyczkę do typescriptu. Po lewej stronie masz ikonki i tam wybierz takie klocki (extensions) i tam wklej sobie tą nazwę `ms-vscode.vscode-typescript-next` i zainstaluj wtyczkę.

2023-04-19 16:18 UTC, des1ro commented
Need to check after applied changes

2023-04-19 16:22 UTC, des1ro commented on src/user/user.routing.ts
> +  const idd: number = parseInt(id);
Dobrze, dodane. Chciałem wszędzie deklarować rodzaj zmiennej, a faktycznie takie powtarzanie nie jest potrzebne.

2023-04-20 12:40 UTC, merged