Pa 11 create and update user
TastyKawusia/PartyApp pull request #12
Opened 2023-04-21 15:11 UTC by des1ro

2023-04-23 12:29 UTC, adamsmichal requested changes

2023-04-23 12:29 UTC, adamsmichal commented on src/user/user.controler.ts
> +export async function postUser(req: Request, res: Response) {
POST i PUT to nazwy metod HTTP więc tutaj powinniśmy nazwać createUser i updateUser

2023-04-23 12:29 UTC, adamsmichal commented on src/user/user.controler.ts
> +  fs.writeFileSync(DB_FILE_PATH, same); // Ogólnie działa tylko tym sposobem nie dodaje do bazy danych tylko czyszcze i tworzę nową
Ogólnie to git tylko tutaj  i w update używasz funkcji synchronicznej czyli na czas zapisu blokujesz kod. A powinno być asynchronicznie

2023-04-23 12:29 UTC, adamsmichal commented on src/user/user.routing.ts
> +routes.put("/user/:id/:name/:age", putUser);
Zarówno w POST jak i w PUT wszystkie parametry przesyłamy w body a nie w paramsach. W PUT chcemy w paramsie przesłać tylko id `/user/:id` a cała resza powinna iść w request body

2023-04-25 22:46 UTC, adamsmichal requested changes

2023-04-25 22:46 UTC, adamsmichal commented on src/user/user.validation.ts
> +  id: Joi.number().integer(),
Id nie musimy walidować bo go tutaj nie przekazujemy tylko tworzymy wewnątrz naszej apki

2023-04-25 22:46 UTC, adamsmichal commented on src/user/user.routing.ts
> +routes.put("/user/:id", UpdateUser);
Nazwy funkcji według konwencji nazewniczej powinny być z małej litery

2023-04-25 22:46 UTC, adamsmichal commented on src/user/user.controler.ts
> +  }
Tutaj dwa razy powtarzamy ten sam błąd `res.status(500).send("Create User error");` co prawda z innym kodem ale still. Dla ujednolicenia kodu lepiej będzie użyć async/await bo to bardziej nowoczesne podejście. Wtedy wystarczy `await fs.writeFile(DB_FILE_PATH, newDbContent);` i jeśli będzie błąd to wpadnie od do catcha

2023-04-25 22:46 UTC, adamsmichal commented on src/user/user.controler.ts
> +    const newDbContent = JSON.stringify(dbContent);
Ja bym to wyniósł ponad try {} żeby było bardziej czytelne. Zobacz tylko jak się zachowa `await schema.validateAsync({ id: id, name: data.name, age: data.age });` jeśli będzie ponad try

2023-04-25 22:46 UTC, adamsmichal commented on src/user/user.controler.ts
> +    res.status(400).send("Error reading users");
400 oznacza bad request. Czyli jeśli wysyłamy name: 123 a ma być stringiem to wtedy zwracamy 400. Tutaj bardziej pasuje 500 które oznacza bliżej nieokreślony błąd serwera

2023-04-26 20:07 UTC, des1ro commented
Skończę kiedyś tę pr? XD

2023-06-16 15:04 UTC, merged